version: '3.7'
services:
    db:
        container_name: db
        image: mysql
        command: ["--default-authentication-plugin=mysql_native_password"]
        ports:
            - "3308:3306"
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: symfony
            MYSQL_USER: symfony
            MYSQL_PASSWORD: symfony
        networks:
            - db
    adminer:
        image: adminer
        environment:
            ADMINER_DEFAULT_DB_DRIVER: mysql
            ADMINER_DEFAULT_DB_HOST: db
            ADMINER_DEFAULT_DB_NAME: symfony
            ADMINER_PLUGINS: tables-filter tinymce
        ports:
            - 8088:8080
        depends_on:
            - db
        networks:
            - db
    php:
        container_name: php-fpm
        build: ./php-fpm
        ports:
            - "9000:9001"
        volumes:
            - ./symfony:/var/www/symfony:cached
        depends_on: 
            - db
        networks:
            - db
            - php
    nginx:
        container_name: nginx
        build: ./nginx
        ports:
            - "88:80"
        depends_on: 
            - php
        networks:
            - php
        volumes:
            - ./symfony:/var/www/symfony:cached
networks:
    db:
    php:
